// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sd} from '../models';

export function LoadFromFile():Promise<boolean>;

export function Predict(arg1:string,arg2:sd.FullParams):Promise<Array<string>>;

export function PredictImage(arg1:string,arg2:string,arg3:sd.FullParams):Promise<Array<string>>;

export function SaveImage(arg1:string):Promise<boolean>;

export function SetOptions(arg1:sd.Options):Promise<void>;
