// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadFromFile() {
  return window['go']['main']['App']['LoadFromFile']();
}

export function Predict(arg1) {
  return window['go']['main']['App']['Predict'](arg1);
}

export function PredictImage(arg1, arg2) {
  return window['go']['main']['App']['PredictImage'](arg1, arg2);
}

export function ReNewInstance() {
  return window['go']['main']['App']['ReNewInstance']();
}

export function SetOptions(arg1) {
  return window['go']['main']['App']['SetOptions'](arg1);
}
