// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirPath(arg1) {
  return window['go']['main']['App']['GetDirPath'](arg1);
}

export function GetFilePath(arg1) {
  return window['go']['main']['App']['GetFilePath'](arg1);
}

export function GetInitImage() {
  return window['go']['main']['App']['GetInitImage']();
}

export function GetOptions() {
  return window['go']['main']['App']['GetOptions']();
}

export function LoadFromFile() {
  return window['go']['main']['App']['LoadFromFile']();
}

export function Predict(arg1, arg2) {
  return window['go']['main']['App']['Predict'](arg1, arg2);
}

export function PredictImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['PredictImage'](arg1, arg2, arg3);
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SetOptions(arg1) {
  return window['go']['main']['App']['SetOptions'](arg1);
}

export function StartBackend() {
  return window['go']['main']['App']['StartBackend']();
}
