name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
#          { name: stable-diffusion-desktop, platform: linux/amd64, os: ubuntu-latest },
          { name: stable-diffusion-desktop, platform: windows/amd64, os: windows-latest },
          { name: stable-diffusion-desktop, platform: darwin/universal, os: macos-latest }
        ]

    runs-on: ${{ matrix.build.os }}
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.21'
